### ISSUE TITLE
Dataset with multiple classes

### ISSUE THREAD

**Issue by chrisbitter** [cviviers/YOLOv5-6D-Pose#25]
Hello,

first of all, great project. Got my first custom model running faster than I expected :)

What I'm currently struggling with is training with multiple classes.

In the Readme theres a todo: "Multi-object Pose", so maybe what I'm trying is not even possible yet.

My first attempt was this custom config.yaml 

```yaml

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ["./data/brick/brick4x2/train.txt", "./data/brick/brick2x2/train.txt"]
val: ["./data/brick/brick4x2/test.txt", "./data/brick/brick2x2/test.txt"]
test: ["./data/brick/brick4x2/test.txt", "./data/brick/brick2x2/test.txt"]

mesh: ["./data/brick/brick4x2/brick4x2.ply", "./data/brick/brick2x2/brick2x2.ply"]
tr_range: ["./data/brick/brick4x2/training_range.txt", "./data/brick/brick2x2/training_range.txt"]
backup : ./backup/brick
names : ["brick4x2", "brick2x2"]

background_path: "./data/VOCdevkit/VOC2012/JPEGImages"
coords: 18

gpus : 0

nc: 2  # number of classes

fx: 949.8506622
fy: 949.70506462
u0: 627.84604663
v0: 354.06980147
```

However, this line throws an error due to path being a list.
https://github.com/cviviers/YOLOv5-6D-Pose/blob/6b982c6043bb41ab53da804e8d09300ed5204261/utils/datasets.py#L489

Any chance I can get this running without too much overhead?
